/** @type {import('tailwindcss').Config} */
module.exports = {
  content: ['./src/**/*.{js,jsx,ts,tsx}'],
  presets: [require('nativewind/preset')],
  theme: {
    extend: {
      colors: {
        bg: 'var(--color-bg)',
        'bg-elevated': 'var(--color-bg-elevated)',
        surface: 'var(--color-surface)',
        border: 'var(--color-border)',
        text: 'var(--color-text)',
        'text-muted': 'var(--color-text-muted)',
        'text-disabled': 'var(--color-text-disabled)',
        icon: 'var(--color-icon)',
        primary: 'var(--color-primary)',
        'primary-pressed': 'var(--color-primary-pressed)',
        'primary-soft': 'var(--color-primary-soft)',
        'on-primary': 'var(--color-on-primary)',
        secondary: 'var(--color-secondary)',
        'secondary-soft': 'var(--color-secondary-soft)',
        accent: 'var(--color-accent)',
        favorite: 'var(--color-favorite)',
        chili: 'var(--color-chili)',
        sky: 'var(--color-sky)',
        linen: 'var(--color-linen)',
        peach: 'var(--color-peach)',
        butter: 'var(--color-butter)',
        crust: 'var(--color-crust)',
        espresso: 'var(--color-espresso)',
        olive: 'var(--color-olive)',
        sage: 'var(--color-sage)',
      },
      fontFamily: {
        sans: ['Inter_500Medium'],
        'sans-semibold': ['Inter_600SemiBold'],
        'sans-bold': ['Inter_700Bold'],
        'sans-extrabold': ['Inter_800ExtraBold'],
        mono: ['Inter_500Medium'],
        'mono-semibold': ['Inter_600SemiBold'],
        'mono-bold': ['Inter_700Bold'],
      },
      borderRadius: {
        card: '16px',
        cta: '28px',
        icon: '14px',
        sheet: '28px',
      },
    },
  },
  plugins: [],
};
