import type { RecipeView } from '@/features/recipes/types';

function ing(
  recipeId: string,
  index: number,
  quantity: number,
  unit: string,
  name: string,
  category: RecipeView['ingredients'][number]['category'],
) {
  return {
    id: `${recipeId}:ing:${index}`,
    name,
    quantity,
    unit: unit || null,
    preparation: null,
    optional: false,
    category,
    confidence: 1,
  };
}

function step(
  recipeId: string,
  order: number,
  stage: RecipeView['steps'][number]['stage'],
  instruction: string,
  ingredientHint: string | null,
  durationSeconds: number,
) {
  return {
    id: `${recipeId}:step:${order}`,
    stepOrder: order,
    instruction,
    durationSeconds: durationSeconds || null,
    temperature: null,
    stage,
    ingredientHint: ingredientHint || null,
    confidence: 1,
  };
}

export const SEED_RECIPES: RecipeView[] = [
  {
    id: 'seed:pistachio',
    origin: 'seed',
    title: 'Pistachio & Lemon Rigatoni',
    description: null,
    sourceType: 'INSTAGRAM',
    sourceLabel: 'Instagram',
    creator: '@noor.cooks',
    originalUrl: 'https://instagram.com/reel/C8xk2Rp9Lm/',
    thumbnailUrl: null,
    placeholder: ['#f5f5f7', '#e0e0e0'],
    minutes: 25,
    difficulty: 'Easy',
    servings: 4,
    cuisine: 'Italian',
    calories: null,
    confidence: 1,
    warnings: [],
    ingredients: [
      ing('seed:pistachio', 0, 320, 'g', 'Rigatoni', 'Pantry'),
      ing('seed:pistachio', 1, 90, 'g', 'Pistachios, shelled', 'Pantry'),
      ing('seed:pistachio', 2, 1, '', 'Lemon', 'Produce'),
      ing('seed:pistachio', 3, 2, '', 'Garlic cloves', 'Produce'),
      ing('seed:pistachio', 4, 60, 'g', 'Pecorino', 'Dairy'),
      ing('seed:pistachio', 5, 3, 'tbsp', 'Olive oil', 'Pantry'),
      ing('seed:pistachio', 6, 1, 'handful', 'Basil', 'Produce'),
      ing('seed:pistachio', 7, 0.5, 'tsp', 'Chilli flakes', 'Spices'),
    ],
    steps: [
      step(
        'seed:pistachio',
        1,
        'PREP',
        'Toast the pistachios in a dry pan until they smell nutty.',
        '90 g Pistachios',
        180,
      ),
      step(
        'seed:pistachio',
        2,
        'PREP',
        'Blitz two thirds of them with the garlic, oil and half the pecorino.',
        '2 Garlic cloves|3 tbsp Olive oil',
        0,
      ),
      step(
        'seed:pistachio',
        3,
        'PREP',
        'Zest the lemon straight into the paste, then squeeze in the juice.',
        '1 Lemon',
        0,
      ),
      step(
        'seed:pistachio',
        4,
        'COOK',
        'Salt the water heavily. Cook the rigatoni until it still bites back.',
        '320 g Rigatoni',
        600,
      ),
      step(
        'seed:pistachio',
        5,
        'COOK',
        'Warm the paste in a wide pan on low — do not let it fry.',
        '0.5 tsp Chilli flakes',
        90,
      ),
      step(
        'seed:pistachio',
        6,
        'FINISH',
        'Add the pasta with a ladle of its water. Toss hard until the sauce clings.',
        '',
        0,
      ),
      step(
        'seed:pistachio',
        7,
        'FINISH',
        'Off the heat, fold through the rest of the pecorino.',
        '60 g Pecorino',
        0,
      ),
      step(
        'seed:pistachio',
        8,
        'SERVE',
        'Plate it, then finish with the chopped pistachios and basil.',
        '1 handful Basil',
        0,
      ),
    ],
  },
  {
    id: 'seed:harissa',
    origin: 'seed',
    title: 'Harissa Butter Chicken Thighs',
    description: null,
    sourceType: 'YOUTUBE',
    sourceLabel: 'YouTube',
    creator: 'Bina Kitchen',
    originalUrl: null,
    thumbnailUrl: null,
    placeholder: ['#fafafc', '#f0f0f0'],
    minutes: 40,
    difficulty: 'Easy',
    servings: 4,
    cuisine: 'North African',
    calories: null,
    confidence: 1,
    warnings: [],
    ingredients: [
      ing('seed:harissa', 0, 6, '', 'Chicken thighs', 'Meat'),
      ing('seed:harissa', 1, 2, 'tbsp', 'Rose harissa', 'Pantry'),
      ing('seed:harissa', 2, 40, 'g', 'Butter', 'Dairy'),
      ing('seed:harissa', 3, 1, '', 'Red onion', 'Produce'),
      ing('seed:harissa', 4, 400, 'g', 'Chickpeas', 'Pantry'),
      ing('seed:harissa', 5, 1, '', 'Lemon', 'Produce'),
    ],
    steps: [
      step(
        'seed:harissa',
        1,
        'PREP',
        'Rub the thighs with harissa and salt. Leave them while the oven heats.',
        '2 tbsp Rose harissa',
        0,
      ),
      step(
        'seed:harissa',
        2,
        'COOK',
        'Skin down in a cold pan, medium heat, until the fat renders and the skin is glass.',
        '6 Chicken thighs',
        720,
      ),
      step(
        'seed:harissa',
        3,
        'COOK',
        'Add the onion and chickpeas around the chicken and slide the pan into the oven.',
        '1 Red onion|400 g Chickpeas',
        900,
      ),
      step(
        'seed:harissa',
        4,
        'FINISH',
        'Swirl the butter into the pan juices with a squeeze of lemon.',
        '40 g Butter',
        0,
      ),
      step(
        'seed:harissa',
        5,
        'SERVE',
        'Spoon the chickpeas out first, chicken on top, juices over everything.',
        '',
        0,
      ),
    ],
  },
  {
    id: 'seed:gnocchi',
    origin: 'seed',
    title: 'Crispy Sheet-Pan Gnocchi',
    description: null,
    sourceType: 'TIKTOK',
    sourceLabel: 'TikTok',
    creator: '@wknd.pan',
    originalUrl: null,
    thumbnailUrl: null,
    placeholder: ['#ffffff', '#d2d2d7'],
    minutes: 30,
    difficulty: 'Easy',
    servings: 3,
    cuisine: 'Italian',
    calories: null,
    confidence: 1,
    warnings: [],
    ingredients: [
      ing('seed:gnocchi', 0, 500, 'g', 'Shelf gnocchi', 'Pantry'),
      ing('seed:gnocchi', 1, 300, 'g', 'Cherry tomatoes', 'Produce'),
      ing('seed:gnocchi', 2, 1, '', 'Courgette', 'Produce'),
      ing('seed:gnocchi', 3, 125, 'g', 'Mozzarella', 'Dairy'),
      ing('seed:gnocchi', 4, 2, 'tbsp', 'Olive oil', 'Pantry'),
    ],
    steps: [
      step(
        'seed:gnocchi',
        1,
        'PREP',
        'Toss the gnocchi, tomatoes and courgette with oil on the hottest tray you own.',
        '500 g Shelf gnocchi',
        0,
      ),
      step(
        'seed:gnocchi',
        2,
        'COOK',
        'Roast without stirring so the gnocchi blister on one side.',
        '',
        1080,
      ),
      step(
        'seed:gnocchi',
        3,
        'FINISH',
        'Tear over the mozzarella and give it three more minutes.',
        '125 g Mozzarella',
        180,
      ),
      step(
        'seed:gnocchi',
        4,
        'SERVE',
        'Straight from the tray, with the tomato juices spooned back over.',
        '',
        0,
      ),
    ],
  },
  {
    id: 'seed:dal',
    origin: 'seed',
    title: 'Weeknight Coconut Dal',
    description: null,
    sourceType: 'GENERIC_WEB',
    sourceLabel: 'Website',
    creator: 'saltandember.com',
    originalUrl: 'https://saltandember.com',
    thumbnailUrl: null,
    placeholder: ['#f5f5f7', '#d2d2d7'],
    minutes: 35,
    difficulty: 'Easy',
    servings: 4,
    cuisine: 'Indian',
    calories: null,
    confidence: 1,
    warnings: [],
    ingredients: [
      ing('seed:dal', 0, 250, 'g', 'Red lentils', 'Pantry'),
      ing('seed:dal', 1, 400, 'ml', 'Coconut milk', 'Pantry'),
      ing('seed:dal', 2, 1, 'tbsp', 'Ginger, grated', 'Produce'),
      ing('seed:dal', 3, 2, 'tsp', 'Cumin seeds', 'Spices'),
      ing('seed:dal', 4, 200, 'g', 'Spinach', 'Produce'),
      ing('seed:dal', 5, 1, '', 'Onion', 'Produce'),
    ],
    steps: [
      step(
        'seed:dal',
        1,
        'PREP',
        'Rinse the lentils until the water runs clear.',
        '250 g Red lentils',
        0,
      ),
      step(
        'seed:dal',
        2,
        'COOK',
        'Soften the onion and ginger, then bloom the cumin until it pops.',
        '2 tsp Cumin seeds',
        240,
      ),
      step(
        'seed:dal',
        3,
        'COOK',
        'Lentils, coconut milk, water. Simmer until it collapses into itself.',
        '400 ml Coconut milk',
        1200,
      ),
      step(
        'seed:dal',
        4,
        'SERVE',
        'Stir the spinach through off the heat so it stays green.',
        '200 g Spinach',
        0,
      ),
    ],
  },
  {
    id: 'seed:galette',
    origin: 'seed',
    title: 'Tomato & Ricotta Galette',
    description: null,
    sourceType: 'INSTAGRAM',
    sourceLabel: 'Instagram',
    creator: '@flour.notes',
    originalUrl: null,
    thumbnailUrl: null,
    placeholder: ['#fafafc', '#e0e0e0'],
    minutes: 55,
    difficulty: 'Medium',
    servings: 6,
    cuisine: 'French',
    calories: null,
    confidence: 0.62,
    warnings: ['Servings and cook time were inferred'],
    ingredients: [
      ing('seed:galette', 0, 250, 'g', 'Plain flour', 'Pantry'),
      ing('seed:galette', 1, 180, 'g', 'Cold butter', 'Dairy'),
      ing('seed:galette', 2, 250, 'g', 'Ricotta', 'Dairy'),
      ing('seed:galette', 3, 500, 'g', 'Ripe tomatoes', 'Produce'),
      ing('seed:galette', 4, 1, 'tbsp', 'Thyme', 'Produce'),
    ],
    steps: [
      step(
        'seed:galette',
        1,
        'PREP',
        'Rub the butter into the flour, leaving visible flecks. Chill.',
        '180 g Cold butter',
        1800,
      ),
      step(
        'seed:galette',
        2,
        'PREP',
        'Salt the sliced tomatoes and let them drain.',
        '500 g Ripe tomatoes',
        900,
      ),
      step(
        'seed:galette',
        3,
        'COOK',
        'Ricotta on the pastry, tomatoes on top, edges folded in.',
        '250 g Ricotta',
        0,
      ),
      step(
        'seed:galette',
        4,
        'SERVE',
        'Bake until the base is properly bronze, then rest before cutting.',
        '',
        1500,
      ),
    ],
  },
  {
    id: 'seed:congee',
    origin: 'seed',
    title: 'Ginger Scallion Congee',
    description: null,
    sourceType: 'GENERIC_WEB',
    sourceLabel: 'Note',
    creator: 'You',
    originalUrl: null,
    thumbnailUrl: null,
    placeholder: ['#f0f0f0', '#d2d2d7'],
    minutes: 45,
    difficulty: 'Easy',
    servings: 2,
    cuisine: 'Chinese',
    calories: null,
    confidence: 1,
    warnings: [],
    ingredients: [
      ing('seed:congee', 0, 150, 'g', 'Jasmine rice', 'Pantry'),
      ing('seed:congee', 1, 1, 'l', 'Chicken stock', 'Pantry'),
      ing('seed:congee', 2, 30, 'g', 'Ginger', 'Produce'),
      ing('seed:congee', 3, 4, '', 'Spring onions', 'Produce'),
    ],
    steps: [
      step(
        'seed:congee',
        1,
        'PREP',
        'Rinse the rice and bruise the ginger with the flat of a knife.',
        '30 g Ginger',
        0,
      ),
      step(
        'seed:congee',
        2,
        'COOK',
        'Simmer rice and stock low and slow until the grains give up.',
        '1 l Chicken stock',
        2400,
      ),
      step(
        'seed:congee',
        3,
        'FINISH',
        'Season harder than feels right — congee swallows salt.',
        '',
        0,
      ),
      step(
        'seed:congee',
        4,
        'SERVE',
        'Pile on the scallions and a spoon of chilli oil.',
        '4 Spring onions',
        0,
      ),
    ],
  },
];

export function getSeedRecipe(id: string): RecipeView | undefined {
  return SEED_RECIPES.find((recipe) => recipe.id === id);
}
